name: Publish to NPM Registry

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  publish-npm:
    name: Publish to NPM registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        working-directory: app
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
